/**
 * Amazon Order Monitor — personal email relay.
 * Version 1.0.1
 *
 * You deploy this in YOUR OWN Google account; the extension POSTs order
 * updates to it and it emails them to you (self-to-self). Nothing is shared
 * with anyone: the sending authority, the data, and the inbox are all yours.
 *
 * Deploy (one time, ~5 minutes — see the extension README for details):
 *  1. Go to https://script.new while logged into the Google account that
 *     should receive the emails.
 *  2. Replace the default code with this entire file. Save (Ctrl+S).
 *     Click the project name top-left ("Untitled project") and rename it
 *     to something recognizable, e.g. "Amazon Emails".
 *  3. Project Settings (gear icon) -> Script Properties -> Add property:
 *       Property: SHARED_SECRET
 *       Value:    the secret generated by the extension's Options page
 *  4. Deploy -> New deployment -> gear next to "Select type" -> Web app:
 *       Description:    aom relay
 *       Execute as:     Me
 *       Who has access: Anyone
 *     ("Anyone" is required because the extension's POST carries no Google
 *      authentication; the URL + shared secret are the credentials instead.)
 *  5. Authorize when prompted (the only scary-sounding grant is "send email
 *     as you" — that is exactly what this script is for).
 *  6. Copy the Web app URL (ends in /exec) into the extension's Options.
 *
 * Security model:
 *  - The URL and secret are two bearer values, not "two-factor auth". Keep
 *    both private; rotate BOTH (new deployment + new secret) if exposed.
 *  - Secret lives in Script Properties, never in this code and never in git.
 *  - Recipient is derived server-side (the deploying account) — a caller
 *    can never redirect mail elsewhere. With both bearer values an attacker
 *    can still burn your daily quota / drown real alerts (self-spam), and
 *    with the URL alone they can waste Apps Script executions. The rate
 *    limit bounds the damage.
 *  - Rate limit: at most 20 emails per clock hour, enforced atomically
 *    under a script lock (concurrent requests can't slip past it), on top
 *    of the extension's own 20/day cap and Google's ~100/day consumer quota.
 *  - Oversized or malformed requests are rejected before any real work.
 *  - Subject/body are sanitized and sent as PLAIN TEXT (no HTML injection).
 *  - All responses are HTTP 200 (an Apps Script web app limitation); the
 *    real status is the "ok" flag in the JSON body.
 */

// Keep in sync with the "Version" line in the header comment. Echoed in
// authorized responses so the extension can display which relay code is
// actually deployed (deployment numbers are Apps Script's own versioning;
// this constant is the human-facing one).
var RELAY_VERSION = "1.0.1";

var MAX_PER_HOUR = 20;
var MAX_BODY_BYTES = 64000;

function doPost(e) {
  var out;
  try {
    var raw = e && e.postData && e.postData.contents;
    if (!raw || raw.length > MAX_BODY_BYTES) {
      out = { ok: false, error: "bad_request" };
    } else {
      var data = JSON.parse(raw);
      var secret = PropertiesService.getScriptProperties().getProperty("SHARED_SECRET");
      if (!secret || !data || typeof data.secret !== "string" || data.secret !== secret) {
        out = { ok: false, error: "unauthorized" };
      } else {
        out = sendUnderLock_(data);
      }
    }
  } catch (err) {
    out = { ok: false, error: "bad_request" };
  }
  return ContentService.createTextOutput(JSON.stringify(out))
    .setMimeType(ContentService.MimeType.JSON);
}

// The check-and-increment on the counter must be atomic: without the lock,
// N parallel requests could all read the same count and all send.
function sendUnderLock_(data) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(5000);
  } catch (err) {
    return { ok: false, error: "busy" };
  }
  try {
    if (rateLimited_()) {
      return { ok: false, error: "rate_limited", version: RELAY_VERSION };
    }
    var subject = String(data.subject || "(no subject)")
      .slice(0, 200)
      .replace(/[\r\n]/g, " ");
    var body = String(data.body || "").slice(0, 20000);
    MailApp.sendEmail(Session.getEffectiveUser().getEmail(), subject, body);
    // version only in authorized responses — anonymous probes learn nothing
    return { ok: true, remaining: MailApp.getRemainingDailyQuota(), version: RELAY_VERSION };
  } finally {
    lock.releaseLock();
  }
}

// Fixed-window cap: at most MAX_PER_HOUR sends per clock hour. (A fixed
// window, not a rolling one — documented as such; atomicity comes from the
// script lock in sendUnderLock_.)
function rateLimited_() {
  var cache = CacheService.getScriptCache();
  var key = "aom-count-" + Math.floor(Date.now() / 3600000);
  var count = Number(cache.get(key) || 0);
  if (count >= MAX_PER_HOUR) return true;
  cache.put(key, String(count + 1), 3600);
  return false;
}
